name: Welcome to github-actions
on:
 push:
  branches:
   - release
  
jobs:
 say-hello:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: Print Priya
     run: echo "Hello Mom how are you"
