name: Docker Hub Login

on:
  push:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check Secret Exists
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest .

      - name: Check Secret Exists
        run: | 
        
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "DOCKERHUB_USERNAME is missing"
          exit 1
          else
          echo "DOCKERHUB_USERNAME is configured"
          fi
    
