name: Hello Master

on:
  push:
    branches:
      - release
  
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Display Date
        run: date

      - name: Success Message
        run: echo "GitHub Actions pipeline completed successfully!"
